export let DATA_GET_FULFILLED = "DATA_GET_FULFILLED";
export let DATA_GET = "DATA_GET";
export let DATA_GET_PENDING = "DATA_GET_PENDING";
export let UPDATE_FILTERED_APARTS = "UPDATE_FILTERED_APARTS";
export let UPDATE_FAVORITES = "UPDATE_FAVORITES";
export let UPDATE_FILTERS = "UPDATE_FILTERS";
