export const DATA_GET_FULFILLED = "DATA_GET_FULFILLED";
export const DATA_GET = "DATA_GET";
export const DATA_GET_PENDING = "DATA_GET_PENDING";
export const UPDATE_FILTERED_APARTS = "UPDATE_FILTERED_APARTS";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
