let DATA_GET = "DATA_GET";
let DATA_GET_PENDING = "DATA_GET_PENDING";
let UPDATE_FILTERED_APARTS = "UPDATE_FILTERED_APARTS";
let UPDATE_FAVORITES = "UPDATE_FAVORITES";
let UPDATE_FILTERS = "UPDATE_FILTERS";
